version: '3.7'

services:
  inventory-management-ui:
    image: inventory-management-ui:0.1
    build: .
    container_name: inventory-management-ui-dev
    hostname: inventory-management-ui.local
    working_dir: /work
    ports:
      - '5900:5900' # Used when running CRA's dev server
    volumes:
      - ..:/work
      # Allow AWS CLI and other tools to read an AWS profile
      #  - ~/.aws:/home/node/.aws
    environment:
      - ENVIRONMENT=local
    networks:
      - private

  inventory-management-cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    container_name: inventory-management-cypress
    hostname: inventory-management-cypress.local
    working_dir: /work
    command: sleep infinity
    volumes:
      - ..:/work
    environment:
      - APP_BASEURL=http://inventory-management-ui:5900
    depends_on:
      - inventory-management-ui
    networks:
      - private

networks:
  private:
