name: Inventory Management UI tests

on:
  push:
    branches: [ main ]

jobs:
  tests:
    name: Tests configuration
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: .
    steps:
    - uses: actions/checkout@v3
    - name: Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:unit

